title: Zach Teitler
email: "zteitler@gmail.com"
description: >
  Department of Mathematics,
  Boise State University,
  1910 University Dr,
  Boise, ID 83725-1555.
url: "https://zteitler.github.io"
baseurl: ""
github_username: zteitler

repository: "zteitler/zteitler.github.io"
permalink: /:categories/:title/

theme: minima
markdown: kramdown
kramdown:
  parse_block_html: true

#plugins:
#  - jekyll-feed
#  - jekyll-sitemap
excerpt_separator: <!--more-->

# main menu
header_pages:
  - research.md
  - teaching.md
  - advising.md
  - vitae.md

collections:
  courses:
    output: true
  publications:
    output: true
  unpublished:
    output: true
  software:

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: mypost

exclude:
  - Gemfile
  - Gemfile.lock
